services:
  algorithm:
    image: ai
    container_name: Algorithm
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
    user: "${UID}:${GID}"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
